wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [40, 40]
    rows: [13, 13, 4]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Vancouver: "America/Vancouver"
        New York: "America/New York"
      position:
        top: 5
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    security:
      enabled: true
      position:
        top: 4
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
    textfile:
      enabled: true
      filePath: "~/.config/wtf/quote.txt"
      position:
        top: 4
        left: 3
        height: 2
        width: 1
      refreshInterval: 3600
    git:
      commitCount: 5
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 0
        left: 3
        height: 2
        width: 2
      refreshInterval: 8
      repositories:
      - "/Users/james/software/rust/pkvstore/"
      - "/Users/james/software/rust/stocks/"
    ipinfo:
      colors:
        name: red
        value: white
      enabled: true
      position:
        top: 5
        left: 1
        height: 1
        width: 1
      refreshInterval: 150
    hibp:
      accounts:
      - jamesleahy314@gmail.com
      - jamesleahy@uvic.ca
      colors:
        ok: "green"
        pwned: "red"
      enabled: true
      position:
        top: 4
        left: 1
        height: 1
        width: 1
      refreshInterval: 43200
      since: "2019-06-22"
    spotify:
      enabled: true
      position:
        top: 5
        left: 2
        height: 1
        width: 1
      refreshInterval: 0
    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "todo.yml"
      position:
        top: 4
        left: 4
        height: 2
        width: 1
      refreshInterval: 3600
    gcal:
      colors:
        title: "red"
        description: "lightblue"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "chriscummer@me.com"
      enabled: true
      eventCount: 12
      multiCalendar: true
      position:
        top: 0
        left: 0
        height: 4
        width: 1
      refreshInterval: 300
      secretFile: "~/.config/wtf/gcal/client_secret.json"
      showDeclined: true
      timezone: "America/Vancouver"
      withLocation: true
    feedreader:
      enabled: true
      feeds:
      - https://lobste.rs/rss
      - http://dtrace.org/blogs/feed/
      - https://lwn.net/headlines/rss
      feedLimit: 10
      position:
        top: 0
        left: 1
        height: 1
        width: 2
      refreshInterval: 300
